"""improvement proposals table

Revision ID: 19c6e2485c2d
Revises: bd438f5ab4cf
Create Date: 2026-09-18 04:39:24.512974+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# 🔴 Necessary. Alembic autogenerate renders PostgreSQL-specific types as
# `postgresql.JSONB(...)` / `postgresql.ARRAY(...)` but does NOT emit the
# import for them. Without this line the migration raises NameError at
# `alembic upgrade head` time — i.e. only when someone actually runs it.
from sqlalchemy.dialects import postgresql

revision: str = "19c6e2485c2d"
down_revision: str | None = "bd438f5ab4cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "improvement_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("target_component", sa.String(length=128), nullable=False),
        sa.Column("observed_problem", sa.Text(), nullable=False),
        sa.Column("error_class", sa.String(length=32), nullable=False),
        sa.Column("supporting_experience_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("counterexamples", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("proposed_change", sa.Text(), nullable=False),
        sa.Column("expected_benefit", sa.Text(), nullable=False),
        sa.Column("possible_regressions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("applicability", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("evaluation_plan", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("success_metrics", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("rollback_conditions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("approval_level", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "approval_level IN ('none', 'system', 'user', 'user_and_review')",
            name=op.f("ck_improvement_proposals_approval_level_valid"),
        ),
        sa.CheckConstraint(
            "error_class IN ('factual_error', 'reasoning_error', 'conceptual_error', 'evidence_error', 'calibration_error', 'scope_error', 'value_substitution', 'user_model_error', 'expression_error', 'process_error', 'memory_error', 'unknown_error')",
            name=op.f("ck_improvement_proposals_error_class_valid"),
        ),
        sa.CheckConstraint(
            "expected_benefit <> ''",
            name=op.f("ck_improvement_proposals_expected_benefit_non_empty"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_evaluation', 'evaluated', 'rejected', 'approved_for_manual_trial')",
            name=op.f("ck_improvement_proposals_status_valid"),
        ),
        sa.CheckConstraint(
            "target_component <> ''",
            name=op.f("ck_improvement_proposals_target_component_non_empty"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_improvement_proposals_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_improvement_proposals")),
    )
    op.create_index(
        "ix_improvement_proposals_component",
        "improvement_proposals",
        ["target_component"],
        unique=False,
    )
    op.create_index(
        "ix_improvement_proposals_error_class",
        "improvement_proposals",
        ["error_class"],
        unique=False,
    )
    op.create_index(
        "ix_improvement_proposals_status_created",
        "improvement_proposals",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_improvement_proposals_status_created", table_name="improvement_proposals")
    op.drop_index("ix_improvement_proposals_error_class", table_name="improvement_proposals")
    op.drop_index("ix_improvement_proposals_component", table_name="improvement_proposals")
    op.drop_table("improvement_proposals")
    # ### end Alembic commands ###
