"""initial schema: events, cognitive_rounds, idempotency_keys

Revision ID: 4f56217b991c
Revises:
Create Date: 2026-09-17 14:46:41.126134+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4f56217b991c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cognitive_rounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("trigger_event_id", sa.UUID(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("depth_level", sa.String(length=8), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_calls_used", sa.Integer(), nullable=False),
        sa.Column("metacognitive_loops", sa.Integer(), nullable=False),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("failure_stage", sa.String(length=64), nullable=True),
        sa.Column("error_category", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "error_category IN ('factual_error', 'reasoning_error', 'conceptual_error', 'evidence_error', 'calibration_error', 'scope_error', 'value_substitution', 'user_model_error', 'expression_error', 'process_error', 'memory_error', 'unknown_error')",
            name=op.f("ck_cognitive_rounds_error_category_valid"),
        ),
        sa.CheckConstraint(
            "model_calls_used <= (budget ->> 'max_model_calls')::int",
            name=op.f("ck_cognitive_rounds_model_calls_within_budget"),
        ),
        sa.CheckConstraint(
            "state <> 'completed' OR (stop_reason IS NOT NULL AND stop_reason <> '')",
            name=op.f("ck_cognitive_rounds_completed_requires_stop_reason"),
        ),
        sa.CheckConstraint(
            "state <> 'failed' OR (failure_stage IS NOT NULL AND error_category IS NOT NULL)",
            name=op.f("ck_cognitive_rounds_failed_requires_diagnostics"),
        ),
        sa.CheckConstraint(
            "state IN ('created', 'triaging', 'framing', 'retrieving', 'analyzing', 'deliberating', 'metacognitive_review', 'synthesizing', 'responding', 'completed', 'waiting_for_evidence', 'suspended', 'failed', 'cancelled')",
            name=op.f("ck_cognitive_rounds_state_valid"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_cognitive_rounds_completed_not_before_started"),
        ),
        sa.CheckConstraint(
            "metacognitive_loops >= 0",
            name=op.f("ck_cognitive_rounds_metacognitive_loops_non_negative"),
        ),
        sa.CheckConstraint(
            "model_calls_used >= 0", name=op.f("ck_cognitive_rounds_model_calls_non_negative")
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_cognitive_rounds_updated_not_before_created")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_cognitive_rounds_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cognitive_rounds")),
    )
    op.create_index(
        "ix_cognitive_rounds_conversation", "cognitive_rounds", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_cognitive_rounds_user_state", "cognitive_rounds", ["user_id", "state"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("cognitive_round_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("trust_level", sa.String(length=16), nullable=False),
        sa.Column("sensitivity", sa.String(length=24), nullable=False),
        sa.Column("model_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system', 'model', 'external')",
            name=op.f("ck_events_actor_type_valid"),
        ),
        sa.CheckConstraint(
            "sensitivity IN ('public', 'internal', 'personal', 'sensitive', 'highly_sensitive')",
            name=op.f("ck_events_sensitivity_valid"),
        ),
        sa.CheckConstraint(
            "trust_level IN ('untrusted', 'low', 'medium', 'high', 'verified')",
            name=op.f("ck_events_trust_level_valid"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_events_recorded_not_before_occurred")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("sequence", name=op.f("uq_events_sequence")),
    )
    op.create_index("ix_events_correlation_id", "events", ["correlation_id"], unique=False)
    op.create_index(
        "ix_events_round_sequence", "events", ["cognitive_round_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_events_type_recorded", "events", ["event_type", "recorded_at"], unique=False
    )
    op.create_index("ix_events_user_sequence", "events", ["user_id", "sequence"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("cognitive_round_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key <> ''", name=op.f("ck_idempotency_keys_key_non_empty")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        "ix_idempotency_keys_created_at", "idempotency_keys", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_idempotency_keys_created_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_events_user_sequence", table_name="events")
    op.drop_index("ix_events_type_recorded", table_name="events")
    op.drop_index("ix_events_round_sequence", table_name="events")
    op.drop_index("ix_events_correlation_id", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_cognitive_rounds_user_state", table_name="cognitive_rounds")
    op.drop_index("ix_cognitive_rounds_conversation", table_name="cognitive_rounds")
    op.drop_table("cognitive_rounds")
    # ### end Alembic commands ###
