"""long-term memory tables with pgvector

Revision ID: bd438f5ab4cf
Revises: 4f56217b991c
Create Date: 2026-09-17 19:14:56.061524+00:00

阶段 5：长期记忆。新增两张表：

* ``memories`` —— 记忆主表（任务书 §5.11 的全部字段 + 乐观锁版本）；
* ``memory_embeddings`` —— 向量索引（任务书 §10.5「向量索引同步删除」）。

🔴 **向量为什么单独一张表**：逻辑删除只把 ``status`` 改成 ``deleted``，
行还在；若向量是 ``memories`` 上的一列，它就**仍然留在索引里**，
"删了还检索得到"是否发生完全取决于每一次查询是否记得加状态过滤。
独立成表之后，删除传播是一次真实执行过的 ``DELETE``（见 ADR-0017）。

⚠️ 两处**必须手工维护**、autogenerate 不会生成的东西：

1. ``CREATE EXTENSION IF NOT EXISTS vector`` —— 没有它，
   建 ``memory_embeddings`` 会直接报类型不存在；
2. ``pgvector`` 的 import —— autogenerate 会把类型渲染成
   ``pgvector.sqlalchemy.vector.VECTOR(...)`` 却**不写 import**，
   于是 ``upgrade head`` 时才 NameError。
   （阶段 2 已经在 ``postgresql.*`` 上栽过一次同样的跟头。）
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# 🔴 Necessary. Alembic autogenerate renders PostgreSQL-specific types as
# `postgresql.JSONB(...)` / `postgresql.ARRAY(...)` but does NOT emit the
# import for them. Without this line the migration raises NameError at
# `alembic upgrade head` time — i.e. only when someone actually runs it.
from sqlalchemy.dialects import postgresql

from ai_psi.providers.embeddings import DEFAULT_EMBEDDING_DIMENSION

revision: str = "bd438f5ab4cf"
down_revision: str | None = "4f56217b991c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 🔴 扩展必须先于表创建。维度写死在列上，因此这里用的是
    # **常量**而不是 ``Settings().embedding_dimension``——
    # 迁移必须可复现：跟着运行时配置变的迁移，在不同机器上会建出不同的库，
    # 而"同一个 revision 在不同环境结构不同"是最难排查的一类问题。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("memory_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_event_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("evidence_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("applicability", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("sensitivity", sa.String(length=24), nullable=False),
        sa.Column("retention_policy", sa.String(length=24), nullable=False),
        sa.Column("access_scope", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("contradicts_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("embedding_version", sa.String(length=64), nullable=True),
        sa.CheckConstraint("content <> ''", name=op.f("ck_memories_content_non_empty")),
        sa.CheckConstraint(
            "memory_type IN ('episodic', 'semantic', 'user_confirmed_fact', "
            "'user_preference', 'user_goal', 'conceptual', 'strategy', "
            "'failure_case', 'self_model')",
            name=op.f("ck_memories_memory_type_valid"),
        ),
        sa.CheckConstraint(
            "retention_policy IN ('permanent', 'long_term', 'session', "
            "'until_superseded', 'user_controlled')",
            name=op.f("ck_memories_retention_policy_valid"),
        ),
        sa.CheckConstraint(
            "sensitivity IN ('public', 'internal', 'personal', 'sensitive', 'highly_sensitive')",
            name=op.f("ck_memories_sensitivity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'superseded', 'disputed', 'expired', "
            "'deleted', 'rejected')",
            name=op.f("ck_memories_status_valid"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('unverified', 'self_reported', 'third_party', "
            "'verified', 'disputed', 'refuted')",
            name=op.f("ck_memories_verification_status_valid"),
        ),
        sa.CheckConstraint(
            "NOT (id = ANY(contradicts_ids))", name=op.f("ck_memories_no_self_contradiction")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_memories_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_memories_valid_until_after_valid_from"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_memories_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index("ix_memories_user_status", "memories", ["user_id", "status"], unique=False)
    op.create_index("ix_memories_user_type", "memories", ["user_id", "memory_type"], unique=False)
    op.create_index("ix_memories_valid_until", "memories", ["valid_until"], unique=False)
    op.create_table(
        "memory_embeddings",
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("embedding", Vector(DEFAULT_EMBEDDING_DIMENSION), nullable=False),
        sa.Column("embedding_version", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "embedding_version <> ''",
            name=op.f("ck_memory_embeddings_embedding_version_non_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_embeddings_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_id", name=op.f("pk_memory_embeddings")),
    )
    op.create_index(
        "ix_memory_embeddings_hnsw",
        "memory_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_memory_embeddings_version", "memory_embeddings", ["embedding_version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_memory_embeddings_version", table_name="memory_embeddings")
    op.drop_index(
        "ix_memory_embeddings_hnsw",
        table_name="memory_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("memory_embeddings")
    op.drop_index("ix_memories_valid_until", table_name="memories")
    op.drop_index("ix_memories_user_type", table_name="memories")
    op.drop_index("ix_memories_user_status", table_name="memories")
    op.drop_table("memories")
    # ⚠️ **刻意不 DROP EXTENSION。**
    #
    # 扩展是数据库级对象，可能被本 schema 之外的表使用；而且
    # `DROP EXTENSION vector` 会连带删掉所有依赖它的列——包括
    # 别人手工建的那些。回滚一个迁移不该有这种射程。
    # ### end Alembic commands ###
